version: 2
jobs:
  build:
    docker:
      - image: gableroux/unity3d:2018.2.6f1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: |
            UNITY_EXECUTABLE="/Applications/Unity/Hub/Editor/2018.2.6f1/Unity.app/Contents/MacOS/Unity" 
            ./local_test.sh
      - run:
          name: Build
          command: |
            UNITY_EXECUTABLE="/Applications/Unity/Hub/Editor/2018.2.6f1/Unity.app/Contents/MacOS/Unity" 
            ./local_build.sh
